ASSUME CS:CODE, DS:DATA
DATA SEGMENT
LIST DB 02H,22H,45H,01H,32H
DATA ENDS
CODE SEGMENT
START:
MOV AX, DATA
MOV DS, AX
MOV AX,0H
MOV CL,04
GO3:      LEA SI,LIST
MOV DL,04H
GO1:      MOV AL,[SI]          
CMP AL,[SI+1]
JC GO2
XCHG AL,[SI+1]
MOV [SI],AL
GO2:      INC SI
DEC DL
JNZ GO1
DEC CL
JNZ GO3
INT 03H
CODE ENDS
END START